version: '3.8'

services:
  apache_frontend_prod:
    container_name: eva-frontend-prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ../src/public_html:/var/www/html
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./urls.js:/var/www/html/config/urls.js
    ports:
      - "80:80"
    networks:
      - frontend_net_prod

networks:
  frontend_net_prod:
    driver: bridge
